# Generated by Django 3.2.15 on 2023-10-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='SendDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование рассылки')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассылать не ранее')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассылать не позднее')),
            ],
            options={
                'verbose_name': 'Дата рассылки',
                'verbose_name_plural': 'Даты рассылок',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=200, verbose_name='Слот времени')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('level', models.CharField(max_length=200, verbose_name='Уровень')),
                ('link_sent', models.BooleanField(default=False, verbose_name='Ссылка на форму отправлена')),
                ('result_sent', models.BooleanField(default=False, verbose_name='Результаты отправлены')),
                ('best_time_slots', models.ManyToManyField(blank=True, related_name='best_time_students', to='projectautomation.TimeSlot', verbose_name='Наиболее подходящие слоты')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='projectautomation.group', verbose_name='Группа')),
                ('ok_time_slots', models.ManyToManyField(blank=True, related_name='ok_time_students', to='projectautomation.TimeSlot', verbose_name='Допустимые слоты')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ПМ')),
                ('time_slots', models.ManyToManyField(max_length=200, related_name='pms', to='projectautomation.TimeSlot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'ПМа',
                'verbose_name_plural': 'ПМы',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='projectautomation.pm', verbose_name='ПМ группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='projectautomation.timeslot', verbose_name='Время группы'),
        ),
    ]
