# Generated by Django 3.2.15 on 2023-10-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, verbose_name='Название Группы')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование рассылки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало проекта')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projectautomation.levels', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Дата рассылки',
                'verbose_name_plural': 'Даты рассылок',
            },
        ),
        migrations.DeleteModel(
            name='SendDate',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='timeslot',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='best_time_slots',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='link_sent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ok_time_slots',
        ),
        migrations.RemoveField(
            model_name='student',
            name='result_sent',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='заполнена ли группа'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='projectautomation.Student', verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Название Группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='trello_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='projectautomation.levels', verbose_name='Уровень'),
        ),
    ]
