# Generated by Django 3.2.15 on 2023-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0002_auto_20231021_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='title',
            field=models.IntegerField(unique=True),
        ),
    ]
