# Generated by Django 3.2.15 on 2023-10-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0003_alter_levels_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
    ]
