# Generated by Django 3.2.15 on 2023-10-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0004_alter_levels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
