# Generated by Django 3.2.15 on 2023-10-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0005_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='trello_id',
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='trello_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projectautomation.pm', verbose_name='ПМ группы'),
        ),
    ]
