# Generated by Django 3.2.15 on 2023-10-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectautomation', '0006_auto_20231022_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projectautomation.project', verbose_name='Проект группы'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='title',
            field=models.IntegerField(max_length=200, verbose_name='Уровни'),
        ),
    ]
